### ISSUE TITLE
Kororaa Epic: rupture set view with embed leaflet map

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/kororaa#11]
- [ ] working link from menu and landing page to the rupture set page
- [x] rupture set page has leaflet map 
- [ ] simple controls as in in Figma mock-up
- [ ] controls bring up geojson fault set
