### ISSUE TITLE
Kororaa Feature: Visitor tracking

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/kororaa#241]
[@Rachel](https://nshmrevisionproject.slack.com/team/U012Y3S07V5)
 we don't have any front end visitor tracking in place, just too little time to make that part of MVP. So API usage (these plots) is the best proxy we have. These API calls (invocations) only occur when user hits a dynamic page (like publications, maps, hazard & spectra). The landing page hits don't show up here at all.
If we do add visitor tracking in future.  then we may be able to back-interpolate the visitor numbers from future metrics. (edited)

**Done when:**
 - [x] we can track accurately the number of page visits for each page
 - [x] same as above but unique visitors
 - [x] Bonus points: visitor demographics (e.g location)
 - [x] Bonus points: make sure Kororaa still works properly if user has adblocking enabled (see discussoin / example https://stackoverflow.com/a/73295380 )

see https://devowl.io/2022/find-out-website-visits/
