### ISSUE TITLE
Kororaa Epic: IFM Solution Viewer

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/kororaa#293]
Users want to be able to explore the Grand Inversion solution ruptures and rates for all branches of the crustal SRM logic tree
- [ ] Kororaa ticket #294 @benjamineac 
- [ ] Kororaa-API tickets https://github.com/GNS-Science/kororaa-graphql-api/issues/59 and  https://github.com/GNS-Science/kororaa-graphql-api/issues/60 @benjamineac and @chrisdicaprio 
- [ ]  Run "solution analysis" on all branches of crustal logic tree @chrisdicaprio
